Fix Dockerfile

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,11 +1,12 @@
+---
 name: CI/CD Pipeline
 
-on:
+"on":
   push:
     branches:
       - main
     tags:
-      - 'v*'
+      - "v*"
   pull_request:
     branches:
       - main
@@ -20,7 +21,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install dependencies
         run: npm install
@@ -47,7 +48,7 @@ jobs:
       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
-          node-version: '20'
+          node-version: "20"
 
       - name: Install dependencies
         run: npm install
@@ -102,16 +103,14 @@ jobs:
     steps:
       - name: Restart Systemd Service
         run: sudo systemctl restart mywebapp.service
-      
       - name: Verify Deployment
         run: |
           sleep 5
-          
-          curl -f -s http://localhost/items || { echo "Service unavailable!"; exit 1; }
-          
-          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost/unknown-path)
+          curl -f -s http://localhost/items || \
+          { echo "Service unavailable!"; exit 1; }
+          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
+          http://localhost/unknown-path)
           if [ "$HTTP_STATUS" -ne 404 ]; then
-            echo "Error in Nginx configuration! Expected 404, got $HTTP_STATUS"
+            echo "Nginx error: Expected 404, got $HTTP_STATUS"
             exit 1
           fi
-          
